name=input("What is your name? ")
age=input("How old are you? ")
location=input("Where are you live? ")
print("Hello, ", name)
print("Your age is ", age)
print("You live in ", location)

print(' '*7,'++++')
print(' '*5,'+      +')
print(' '*3, '+          +')
print(' ', '+              +')
print('', '+    +      +    +')
print('+                  +')
print('+  +            +  +')
print('', '+   +        +   +')
print(' ','+     +  +     +')
print(' '*3,'+          +')
print(' '*5,'+      +')
print(' '*7,'++++')
